// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"KLM_ReturnLabel","status":true,"description":"Return to a \"Go To Label\" statement after it's called!","parameters":{"Console Log":"true","Prefix Value":"\"Return: \"","RETURN Value":"\"RETURN\""}}
];
